### ISSUE TITLE
Large-format HP Designjet 4000 Printer doesn't print.

### ISSUE THREAD

**Issue by Sandplum** [TampereHacklab/Inventaario#65] opened 2023-09-24 11:16 UTC
Something something print heads...
![image](https://github.com/TampereHacklab/Inventaario/assets/143935229/432cd424-a235-405a-851b-1a1710748d0d)
![image](https://github.com/TampereHacklab/Inventaario/assets/143935229/b8f01ced-8109-4e3f-9d0d-eca378039e73)
From Otto: "Might be a connection issue with those printheads"

**Comment by tswfi** [comment] 2023-11-10 11:22
From Otto: Look for HP designjet 4000 printhead kits.  We were talking with tsw about replacing all. There's two set of printheads in the machine

**Comment by tswfi** [comment] 2023-11-10 11:27
https://support.hp.com/au-en/document/c00263211 says these are the product numbers

![image](https://github.com/TampereHacklab/Inventaario/assets/1352132/51436d87-cd1b-42f5-a58b-cca2a6dae1d5)

**Comment by tswfi** [comment] 2023-11-10 11:32
and cleanup procedure from hp https://support.hp.com/nz-en/document/c00264815

**Comment by Sandplum** [comment] 2023-11-10 13:00
![image](https://github.com/TampereHacklab/Inventaario/assets/143935229/39926487-4420-44d8-9638-6c625a0543a3)
![image](https://github.com/TampereHacklab/Inventaario/assets/143935229/eaf05661-faf1-42a6-a9ee-d5691fa1df9f)
![image](https://github.com/TampereHacklab/Inventaario/assets/143935229/44542a32-e789-41c4-834f-38e672f39fde)

**Comment by tswfi** [comment] 2024-02-07 08:28
Spent 40 minutes on the phone with HP support about this.

This printer is so old that there are no replacement parts for it anymore.

New printheads *might* help but they have no idea (as it does not seem to read the serial number it might be something else entirely) 

https://www.dustin.fi/product/5010077707/printheadcleaner-no90-syaani-till-dj-4000 296,98€ for _one_ printhead and it requires both to work... (and probably no return policy for these)

**Comment by sbeach92** [comment] 2024-02-13 14:31
https://h30434.www3.hp.com/t5/Printers-Archive-Read-Only/printhead-appears-to-be-missing-not-detected-or-incorrectly/m-p/8634740/highlight/true#M3377566

Found this... Would try to check later today if there is some web features enabled if some sort of reset would wake it up.

**Comment by sbeach92** [comment] 2024-02-14 10:14
https://www.ebay.com/itm/225163150719

**Comment by brndd** [comment] 2024-02-27 17:25
Cyan printheads swapped. During calibration printer showed no error but leaked black ink everywhere.

**Comment by brndd** [comment] 2024-02-29 20:37
Black ink problem probably caused by the fact that the black printhead cleaners had had their cleaning sponge removed and each were overflowing with black ink. All the overflow was getting sprayed on the other printhead cleaners, on the printheads, and inside of the machine.

Every printhead and printhead cleaner needs to be replaced, excepting maybe the cyan ones which were just replaced, unless they already became soaked with black ink. The printhead cleaners are keyed to the color (not sure there is any real reason to do this other than to inconvenience users) with a physical key on the cartridge.

After that the entire machine needs to be cleaned because there is black ink **everywhere**.

Replacement print heads will cost ca. 200€ if buying out of date stock from eBay. Cleaning the machine will probably take a full day and be frustrating and messy. Lugging the machine to the loading dock and gently pushing it off will take 15 minutes.

**Comment by nuulis** [comment] 2024-03-06 20:05
Yhteisömiitissä ti 5.3.2024 todettiin laite toivottomaksi korjata ja päätettiin laittaa printteri Toriin/vastaavaan "annetaan"-osastolle. Joku saattaa tarvita varaosiksi. Jos ei noin kuukauden sisään tärppää, kone viedään serriin.

Community meeting 5.3.204 decided that machine is too broken to be fixed. It'll be put on Tori.fi "for free" and if nobody wants it in about a month we'll discard it as e-waste.

**Comment by tswfi** [comment] 2024-07-22 08:38
This printer has been decommissioned. Closing the issue

**Closed** 2024-07-22 08:38 UTC
Labels: Työ (Prioriteetti) Normaali, Laite (Printer) HP Designjet 4000 Printer, PrinterTonttu
